### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by gduscher**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gduscher** [comment]
@conda-forge-admin please add user @gduscher

**Comment by gduscher** [comment]
@conda-forge-admin, please update team

**Comment by gduscher** [comment]
@conda-forge-admin please add user@ramav87

**Comment by gduscher** [comment]
@conda-forge-admin, please update team

**Comment by gduscher** [comment]
@conda-forge-admin, please ping conda-forge/core
I am maintainer but do not have write access. Can somebody please help?
Thanks,
Gerd

**Comment by gduscher** [comment]
@conda-forge/core can you please let me know how I can obtain write access to merge this PR?

**Comment by synapticarbors** [comment]
Usually, I thought: 
@conda-forge-admin, please ping team 

would resend the emails that allow you to confirm ownership of the feedstock. Can you check your spam folder in your email to make sure it didn't end up there?

**Comment by synapticarbors** [comment]
Oops, I meant:
@conda-forge-admin, please update team

**Comment by synapticarbors** [comment]
Actually, I think it needed to be done from an issue, as I did in https://github.com/conda-forge/pytemlib-feedstock/issues/8

You should be getting an email confirming ownership.

**Comment by gduscher** [comment]
Works now, without getting an email.
Thanks,
Gerd

**Pull request merged**
